---
title: "Exercise 7"
subtitle: "Applied Statistics, IT University of Copenhagen"
output:
  pdf_document: default
documentclass: article
classoption: a4paper
references:
- id: Verzani2014
  type: book
  title: "Using R for Introductory Statistics"
  author:
  - family: Verzani
    given: John
  issued:
    year: 2014
  publisher: CRC Press
---

# Preparation

-   Read pages 72--77, 236--240 from @Verzani2014.

# Problems

T=Theoretical Exercise, R=R-Exercise

## 1. Sum of Bernoulli Distributed Variables (T)

Let $X$ and $Y$ be two independent random variables where $X \sim \mathrm{Ber}(p)$ and $Y \sim \mathrm{Ber}(q)$. Let $Z=X+Y$. Investigate how $Z$ is distributed by deriving the probability mass function for $Z$.


## 2. Law of large numbers (T)

Assume that you want to simplify your bookkeeping by rounding your expenses to nearest €. Let the rounding error of a single purchase be described by the random variable $X$. Assume that $n$ is the number of purchases you have made during a year.

(a) How is $X$ distributed?

(b) What is the expected rounding error for a single purchase?

(c) What happens to the mean absolute error $\frac{1}{n} \sum_{i=1}^n |X_i|$ when $n$ grows in the light of the law of large numbers?

## 3. Central Limit Theorem (T)

Let $X_1, X_2,\ldots$ be a sequence of independent, identically distributed random variables, with probability density function given by \begin{equation}
f(x) = \left\{\begin{tabular}{ll} $x$, & if $0<x\leq1$ \\ 
                                  $-x + 2$, & if $1<x<2$ \\
                                  0, & otherwise. \end{tabular}\right.
\end{equation} Use central limit theorem to approximate $P(X_1 +X_2 + \ldots + X_{277} > 301)$.

```{r}
# find percentage chance of greater than 3.53 standard deviations above the mean
# in a normal distribution
pnorm(301,277,277^0.5,lower.tail = F)
```

## 4. Sum of Random Variables (R)

Assume you have $n$, independent, uniformly distributed random variables $X_i\sim U(0,1)$, $i=1,2,\ldots,n$. Consider the sum of these random variables $Z=X_1+X_2+...+X_n$. Draw thousand samples for the random variable $Z$ for each $n=1,2,3,4$. Plot the histogram of the samples (`hist`) for each $n$. How do the histograms look like? What happens to the histograms, and hence the probability density of $Z$, when you increase $n$?

## 5. Michelson Experiment (R)

In 1879, A.A. Michelson made a famous experiment to determine the speed of light, the data set is available as `Michelson(HistData)`. The velocity estimates are $v=299000 \mathrm{km}/\mathrm{s} + \delta v$ where $\delta v$ is the velocity value saved in the data set.

(a) Study the examples shown by typing '?Michelson'.

(b) Make density plot of the measurements together with data together with the individual estimates and true speed of light.

(c) Assume that the velocity estimates are independent and identically distributed. Compute an estimate for the speed of light and compare to the true value known today. Add the estimate to the plot.

(d) Use Chebychev's inequality to find out an upper bound for the probability that the speed of light was equal or further away from the value known today.

(e) After looking closer at the data set do you have any reservations about the assumptions made above?
