CREATE TABLE Politician(
	PID INT PRIMARY KEY
);

CREATE TABLE Official(
	OID INT PRIMARY KEY
);

CREATE TABLE Bribes(
	PID INT REFERENCES Politician(PID),
	OID INT REFERENCES Official(OID),
	Why VARCHAR(100) NOT NULL,
	WhenDate DATE,
	PRIMARY KEY(PID, OID, WhenDate)
);

CREATE TABLE Police(
	LID INT PRIMARY KEY,
	PID INT NOT NULL REFERENCES Politician(PID),
	HowMuch INT NOT NULL
);

CREATE TABLE Civilian(
	CID INT PRIMARY KEY
);

CREATE TABLE Arrests(
	CID INT REFERENCES Civilian(CID),
	LID INT REFERENCES Police(LID),
	PRIMARY KEY(CID, LID)
);

CREATE TABLE Mistreats(
	CID INT REFERENCES Civilian(CID),
	LID INT REFERENCES Police(LID),
	How VARCHAR(100) NOT NULL,
	PRIMARY KEY(CID)
);

